spring.application.name=devops-demo

# Expose DevOps/monitoring endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
# Show detailed health status
management.endpoint.health.show-details=always